<?php
if (isset($flash)) {
  if (array_key_exists('success', $flash)) {
    echo $flash['success'][0].'<br>';
  }
}
?>

<form action="/cars" method="get">
  <input type="search" name="term" value="<?= htmlspecialchars($term ?? '')?>" />
  <input type="submit" value="Search" />
</form>
<hr>
<table>
  <?php foreach ($cars as $car): ?>
    <tr>
      <td>
          <?= $car->GetId() ?>
      </td>
      <td>
          <a href="/cars/<?= $car->GetId() ?>/edit"><?= $car->GetMake() ?></a>
      </td>
    </tr>
  <?php endforeach ?>
</table>


<form action="/exit" method="get">
  <input type="submit" value="Выход" />
</form>