<form action="/users" method="get">
  <input type="search" name="term" value="<?= htmlspecialchars($term ?? '')?>" />
  <input type="submit" value="Search" />
</form>
<hr>
<table>
  <?php foreach ($users as $user): ?>
    <tr>
      <td>
          <?= $user['id'] ?>
      </td>
      <td>
          <a href="/users/<?= $user['id'] ?>"><?= $user['name'] ?></a>
      </td>
    </tr>
  <?php endforeach ?>
</table>

